import styled from "@emotion/styled";
import Head from "next/head";
import Button from "../src/components/button";
import DropDown from "../src/components/dropdown";

// const inter = Inter({ subsets: ['latin'] });
const Wrap = styled.div`
  width: 100%;
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: url(/image/camping.jpg) center/cover no-repeat;
`;

const SearchWrap = styled.div`
  position: relative;

  width: calc(100% - 36rem);
  padding: 6rem 2rem;
  background: rgba(255, 255, 255, 0.15);
  border: 0.1rem solid #d3d3d3;
  border-radius: 2rem;
  backdrop-filter: blur(17.4px);
  box-shadow: 0 4px 4px 0 rgba(0, 0, 0, 0.25);

  .review {
    position: absolute;
    right: 0;
    top: -56px;
  }

  h2 {
    font-family: "Times New Roman";
    color: #fff;
    font-size: 5rem;
    text-align: center;
  }
`;

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Go Camping</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrap>
        <SearchWrap>
          <Button className="review">요즘 캠핑 후기 보기</Button>
          <div>
            <h2>Dayily camping</h2>
            <DropDown />
          </div>
        </SearchWrap>
      </Wrap>
    </>
  );
}
